version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/static
        ports:
            - "8000:8000"
        env_file:
            - .env


volumes:
    static_volume: